import { NextRequest } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
// Initialize using the Service Role/Secret Key to bypass RLS policies for server-side API writes
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const supabase = createClient(supabaseUrl, serviceRoleKey)

export async function POST(request: NextRequest) {
  try {
    const { title, description, assigned_to_name, assigned_to_phone, deadline } = await request.json()

    if (!title || !assigned_to_phone) {
      return Response.json({ success: false, error: 'Title and Assignee Phone are required' }, { status: 400 })
    }

    // 1. Resolve team member profile ID by phone number to match schema foreign key
    let assignedToUuid = null
    const cleanPhone = assigned_to_phone.replace(/\D/g, '')

    // Fetch profile (uses service role client to bypass profile read RLS)
    const { data: profile } = await supabase
      .from('profiles')
      .select('id')
      .ilike('phone', `%${cleanPhone.slice(-9)}%`) // Match ending digits for formatting robustness
      .single()

    if (profile) {
      assignedToUuid = profile.id
    }

    // 2. Insert task into Supabase (service role client bypasses RLS policies)
    const { data: task, error: insertError } = await supabase
      .from('tasks')
      .insert([{ 
        title, 
        description: description || null, 
        assigned_to: assignedToUuid, 
        deadline: deadline ? new Date(deadline).toISOString() : null, 
        status: 'Pending' 
      }])
      .select()
      .single()

    if (insertError) throw insertError

    // Task Code generated by database sequence (e.g. #1001)
    const task_code = task.id 

    // 3. WhatsApp Message Trigger (Meta Cloud API Call)
    const whatsappToken = process.env.WHATSAPP_TOKEN || process.env.WHATSAPP_ACCESS_TOKEN
    const whatsappPhoneId = process.env.WHATSAPP_PHONE_NUMBER_ID

    let whatsappResult = null

    if (whatsappToken && whatsappPhoneId) {
      const whatsappResponse = await fetch(
        `https://graph.facebook.com/v18.0/${whatsappPhoneId}/messages`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${whatsappToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            messaging_product: "whatsapp",
            recipient_type: "individual",
            to: cleanPhone,
            type: "text",
            text: {
              body: `Salam ${assigned_to_name || 'Team Member'},\n\nAapka aaj ka task assign ho chuka hai:\n\n🆔 *Task Code:* ${task_code}\n📝 *Title:* ${title}\n📋 *Details:* ${description || 'No details'}\n📅 *Deadline:* ${deadline || 'Today'}\n\n*Task complete karne ke baad is message ka reply karein:* ${task_code} DONE`
            }
          }),
        }
      )
      whatsappResult = await whatsappResponse.json()

      // Send monitoring copy to Admin
      const adminPhone = process.env.ADMIN_WHATSAPP_NUMBER
      if (adminPhone) {
        try {
          const { sendWhatsAppMessage } = await import('@/utils/whatsapp')
          const adminMessage = `*LUMORA MONITORING ALERT:*\n\nTask Assigned to *${assigned_to_name || 'Team Member'}* (${assigned_to_phone}):\n\nTask: "${title}"\n*Task Code: ${task_code}*\n*Deadline:* ${deadline || 'Today'}`
          await sendWhatsAppMessage(adminPhone, adminMessage)
        } catch (err) {
          console.error('[API Tasks Outgoing] Failed to send Admin monitoring copy:', err)
        }
      }
    } else {
      console.warn('[API Tasks] Meta credentials not configured. Skipping WhatsApp message.')
    }

    return Response.json({ success: true, task, whatsappResult })

  } catch (err: any) {
    console.error('[API Tasks] Error:', err)
    return Response.json({ success: false, error: err.message }, { status: 500 })
  }
}
